# Copyright (C) 2023, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

---
- name: Create and start VMs
  hosts: "node1"
  gather_facts: false
  become: true
  tasks:
    - name: "Clone VM {{ item }} from {{ hostvars[item].clone_from  }}"
      cluster_vm:
        name: "{{ item }}"
        command: clone
        src_name: "{{ hostvars[item].clone_from }}"
        force: true
        live_migration: true
        migration_user: "{{ livemigration_user }}"
        enable: true
        pinned_host: "{{ hostvars[item].pinned_host | default(None) }}"
        preferred_host: "{{ hostvars[item].preferred_host | default(None) }}"
        crm_config_cmd: "{{ hostvars[item].crm_config_cmd | default(omit) }}"
        xml: >-
          {{ lookup('template',
          hostvars[item].vm_template,
          template_vars=dict(vm=hostvars[item])) }}
      with_items: "{{ groups['VMs'] }}"
      when: hostvars[item].action=="clone"


